<?xml version="1.0"?>
<package format="3">
  <name>go8010_ros2_driver</name>
  <version>0.1.0</version>
  <description>GO8010 motor RS485 driver</description>
  <maintainer email="maintainer@example.com">maintainer</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>robot_msgs</depend>
  <depend>diagnostic_msgs</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
